# 02 - Data Cleaning

## Objective
Clean the loaded retail dataset by:
- Handling missing values
- Removing duplicates
- Removing cancelled transactions
- Removing invalid quantities and prices
- Creating Revenue feature
- Saving cleaned dataset for further analysis

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv(
    r"C:\Users\91895\OneDrive\Desktop\NeuralRetail\data\processed\combined_retail.csv"
)

print("Dataset Loaded Successfully")
print(df.shape)

df.head()

Dataset Loaded Successfully
(779425, 9)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 779425 entries, 0 to 779424
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  int64
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  object
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  float64
 7   Country      779425 non-null  object
 8   Revenue      779425 non-null  float64
dtypes: float64(3), int64(2), object(4)
memory usage: 53.5+ MB

In [4]:
df.describe(include="all")

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
count,779425.000000,779425,779425,779425.000000,779425,779425.000000,779425.000000,779425,779425.000000
unique,NaN,4631,5283,NaN,34585,NaN,NaN,41,NaN
top,NaN,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,2011-11-14 15:27:00,NaN,NaN,United Kingdom,NaN
freq,NaN,5023,5016,NaN,542,NaN,NaN,700388,NaN
mean,537426.828586,NaN,NaN,13.489370,NaN,3.218488,15320.360461,NaN,22.291823
std,26901.629627,NaN,NaN,145.855814,NaN,29.676140,1695.692775,NaN,227.427075
min,489434.000000,NaN,NaN,1.000000,NaN,0.001000,12346.000000,NaN,0.001000
25%,514483.000000,NaN,NaN,2.000000,NaN,1.250000,13971.000000,NaN,4.950000
50%,536754.000000,NaN,NaN,6.000000,NaN,1.950000,15247.000000,NaN,12.480000
75%,561995.000000,NaN,NaN,12.000000,NaN,3.750000,16794.000000,NaN,19.800000
max,581587.000000,NaN,NaN,80995.000000,NaN,10953.500000,18287.000000,NaN,168469.600000

In [5]:
missing = df.isnull().sum()

missing

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
Revenue        0
dtype: int64

In [6]:
missing_percent = (missing/len(df))*100

missing_percent.sort_values(ascending=False)

Invoice        0.0
StockCode      0.0
Description    0.0
Quantity       0.0
InvoiceDate    0.0
Price          0.0
Customer ID    0.0
Country        0.0
Revenue        0.0
dtype: float64

In [7]:
df = df.dropna(subset=["Customer ID"])

print(df.shape)

(779425, 9)

In [8]:
print("Before:", df.shape)

df.drop_duplicates(inplace=True)

print("After:", df.shape)

Before: (779425, 9)
After: (779425, 9)

In [9]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [10]:
df.dtypes

Invoice                 int64
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
Revenue               float64
dtype: object

In [11]:
df = df[
    ~df["Invoice"].astype(str).str.startswith("C")
]

print(df.shape)

(779425, 9)

In [12]:
df = df[df["Quantity"] > 0]

print(df.shape)

(779425, 9)

In [13]:
df = df[df["Price"] > 0]

print(df.shape)

(779425, 9)

In [14]:
df["Revenue"] = df["Quantity"] * df["Price"]

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [15]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
Revenue        0
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 779425 entries, 0 to 779424
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      779425 non-null  int64
 1   StockCode    779425 non-null  object
 2   Description  779425 non-null  object
 3   Quantity     779425 non-null  int64
 4   InvoiceDate  779425 non-null  datetime64[ns]
 5   Price        779425 non-null  float64
 6   Customer ID  779425 non-null  float64
 7   Country      779425 non-null  object
 8   Revenue      779425 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(3)
memory usage: 53.5+ MB

In [17]:
print(df.shape)

(779425, 9)

In [18]:
os.makedirs(
    r"C:\Users\91895\OneDrive\Desktop\NeuralRetail\data\processed",
    exist_ok=True
)

df.to_csv(
    r"C:\Users\91895\OneDrive\Desktop\NeuralRetail\data\processed\cleaned_retail.csv",
    index=False
)

print("Cleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully

In [19]:
clean_df = pd.read_csv(
    r"C:\Users\91895\OneDrive\Desktop\NeuralRetail\data\processed\cleaned_retail.csv"
)

clean_df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

## Conclusion

Successfully cleaned the Online Retail II dataset by:

- Removed missing Customer IDs
- Removed duplicate transactions
- Removed cancelled invoices
- Removed negative quantities
- Removed negative prices
- Created Revenue feature
- Saved cleaned dataset for future analysis